import type { Metadata } from "next";

import { cn } from "@/src/utils";
import { AppShell, AppShellSection } from "@mantine/core";

import "./globals.css";
import { Providers } from "../components/Providers";
import MainLayoutHeader from "../layouts/main/Header";
import MainLayoutFooter from "../layouts/main/Footer";

export const metadata: Metadata = {
    title: "Zona Mágica",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full",
                "antialiased",
                "font-sans",
            )}
        >
            <head>
                <link
                    rel="shortcut icon"
                    href="/favicon.png"
                    type="image/png"
                />

                <link
                    rel="preconnect"
                    href="https://fonts.googleapis.com"
                ></link>
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin=""
                ></link>
                <link
                    href="https://fonts.googleapis.com/css2?family=Englebert&display=swap"
                    rel="stylesheet"
                ></link>
            </head>
            <body className="min-h-full flex flex-col">
                <Providers>
                    <AppShell>
                        <MainLayoutHeader />
                        {children}
                        <MainLayoutFooter />
                    </AppShell>
                </Providers>
            </body>
        </html>
    );
}
