import type { Metadata } from "next";

import { cn } from "@/src/utils";
import { AppShell, AppShellSection } from "@mantine/core";

import "./globals.css";
import { Providers } from "../components/Providers";
import MainLayoutHeader from "../layouts/main/Header";
import MainLayoutFooter from "../layouts/main/Footer";
import { withBasePath } from "../utils/withBasepath";
import {
    GANoscript,
    GAInit,
    GoogleConsent,
} from "../components/GAnalytics";
import CookieBanner from "../components/ConsentBanner";
import { ConsentManager } from "../components/ConsentManager";

export const metadata: Metadata = {
    title: "Zona Mágica",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full",
                "antialiased",
                "font-sans",
            )}
        >
            <head>
                <GAInit />
                <GoogleConsent />

                <link
                    rel="shortcut icon"
                    href={withBasePath("/favicon.png")}
                    type="image/png"
                />

                <link
                    rel="preconnect"
                    href="https://fonts.googleapis.com"
                ></link>
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin=""
                ></link>
                <link
                    href="https://fonts.googleapis.com/css2?family=Englebert&display=swap"
                    rel="stylesheet"
                ></link>
            </head>
            <body className="min-h-screen flex flex-col">
                <GANoscript />
                <ConsentManager />

                <Providers>
                    <MainLayoutHeader />

                    <main className="flex-1">
                        {children}
                    </main>

                    <MainLayoutFooter />

                    <CookieBanner />
                </Providers>
            </body>
        </html>
    );
}
